version: '3.8'

services:
  db:
    image: yobasystems/alpine-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: raum_security
      MYSQL_USER: raum_user
      MYSQL_PASSWORD: raum_password
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./raum-security-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://raum_user:raum_password@db/raum_security

volumes:
  mariadb_data:
